### ISSUE TITLE
Add type definitions for Typescript

### ISSUE THREAD

**Issue by moshekrup** [arobson/rabbot#117]
I would like to request "type definitions" for Typescript for this library. It would be great to use this library in my Typescript projects.

Thanks.

**Comment by arobson** [comment]
Hi @moshekrup - I haven't honestly had time to give this lib the attention it deserves as it is. I am stuck trying to release v2 because of a broken dependency (it only breaks for Node v6, but still).

If you'd like type definitions, I'll accept a PR for them but I don't use Typescript and don't have time to learn it so I can add definitions.

**Comment by JimiC** [comment]
As I'm using `rabbot` on various work projects, I've been wanting to write those type definitions and have them on `Definitely Typed` repo but something always get's in my way.
