### ISSUE TITLE
custom exchangeTypes not handled

### ISSUE THREAD

**Issue by deejbee** [arobson/rabbot#127]
I'm trying to use the [https://github.com/rabbitmq/rabbitmq-delayed-message-exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) plugin but it must set the exchange type to **x-delayed-message** which is not currently supported by the looks of it.  

Is there a way to do it?

**Comment by alonisser** [comment]
1. This lib actually a wrapper around amqplib, so anything supported by it would be supported here, From a quick look at amqplib docs, also **seems** to support custom exchange Types. So I don't know what you mean by "not currently supported by the looks of it" 
2. Please note that for that to work you would need to verify you actually installed and enabled the plugin, added the custom exchange type, and passed the extra arg option to add exchange creation (("x-delayed-type", "direct"). Also you'll need to verify you have correct rabbitmq and erlang versions since this plugins seems to demand a quite updated version of erlang (higher then the one rabbitmq needs)

If you are trying something which isn't working, please elaborate
