### ISSUE TITLE
Ultra consistent Queue Names without machine/process affiliation

### ISSUE THREAD

**Issue by alonisser** [arobson/rabbot#128]
PR inquiry: Would you be open to a PR along the following lines:
Add to ```addQueue``` ```unique``` option another options: ```named``` which would set the queue name as ```queue_${name}``` thus making it consistent with different machines/processes/etc

If a queue with this name exists, creation should fail

Rational:
Currently Rabbot allows only one queue naming schema which accounts for recovery concerns which is consistent. Unfortunately consistent queue name does not take into account multiple (competing) workers consuming from the same queue setup dynamically (as part of scaling ) in a kubernetes (or similar solution) cluster, where workers (as pods) can be created on different nodes, every  time one is needed (as part of dynamic scaling or perhaps as a container scheduler job)
This makes this use case problematic, since either we don't use persistent queues => and when no worker is up loss messages, OR use persistent queues and handle lots of cleanup somehow (removing not needed queues). 

I already hit this one also when migrated apps from one server to other - having the same app create new queues , and needing to cleanup older queues

What do you say?

**Comment by arobson** [comment]
@alonisser - I get the use case (I use Kubernetes too 😄) Where would `name` be coming from in this case? If it's programmatic, why not just plug it into the code supplying the config block and set `exclusive: true`? (That prevents anyone else from subscribing to the queue). I've encountered this use-case before and if you want to prevent multiple instances of the same service from grabbing the same queue name, use `exclusive` and derive the queue name from something predictable when the service spins up.

I've used etcd, consul and redis all in different cases to coordinate a "service id" that gets tacked on to queues so that the queues won't get lost between container restarts despite host migration.

**Comment by alonisser** [comment]
I think the use case is somewhat different. say I want a single queue (so at most once delivered semantics are kept) with multiple (competing) consumers, which number changes dynamically (with scaling) but the queue should exist even if currently no consumer, so I need a durable, non exclusive (multiple consumers) queue but with a constant name, so it won't create a new queue each time a new pod on a new node is spawned. (Causing the app to process a given message more then once - in multiple queues)

**Comment by arobson** [comment]
@alonisser - the only thing changing is you’re not using the exclusive flag but you’d still need an outside coordinating source to determine the queue postfix. That or you’re using the exact same queuename regardless.

The unique feature is only for cases when Rabbot is using an aspect of the process, hosting environment or a randomizer to generate a queuename that will avoid collisions with any additional instance of the same service. What you are describing is a queue that would be occasionally shared and so the unique feature doesn’t fit your use case at all since you want other instances to be able to occasionally determine the same queuename.

You have several options for how to go about adding a queue where the name is determined programmatically but because they all include an external source to coordinate or share the name, this isn’t a feature I plan to add to Rabbot.

**Comment by alonisser** [comment]
I've might be mislead by the docs, if the unique key word is dropped , would the queue name be just the queue name passed in the options object?  I've checked the source code now and this does seem to be case..  (in ```Topology.prototype.getUniqueName```) Please confirm and if so, I'll push a suggestion for a docs fix later.
Sorry for the trouble

**Comment by arobson** [comment]
Right - using the unique option adds things to the queue name provided in order to differentiate the queue between instances of the service. You still refer to the queue by the name provided in the options (like an alias). Otherwise the name is what gets passed down through to Rabbit.
