### ISSUE TITLE
addConnection Does Not Seem to Return a Promise

### ISSUE THREAD

**Issue by kevinswarner** [arobson/rabbot#22]
The documentation says that addConnection returns a promise, but the returned object does not have a .catch, .then, or .done function. I am just getting familiar with 'rabbot' and 'when', so I may just be overlooking something simple. I was attempting to do something like so...

```
let rabbit = require('rabbot');
rabbit.addConnection({
  user: 'guest',
  pass: 'guest',
  host: '127.0.0.1',
  port: 5672,
  timeout: 2000,
  vhost: '%2f',
  heartbeat: 10
}).done(() => {
  console.log('Connected.');
});
```

I get an error 'rabbit.addConnection(...).done is not a function'.

**Comment by mkozjak** [comment]
+1

```js
var rabbit = require("rabbot")

var test = rabbit.addConnection({
    user: "guest",
    pass: "guest",
    host: '127.0.0.1',
    port: 5672,
});

var pro = new Promise(function(resolve, reject) {})

if (test instanceof Promise) {
    console.log('promise')
}

if (pro instanceof Promise) {
    console.log('promise')
}

// outputs 'pro promise'
```

**Comment by iamjochem** [comment]
hi there, 

`addConnection()` is returning an instance of [Topology](https://github.com/arobson/rabbot/blob/master/src/topology.js#L44) - probably an idea to changes the docs to reflect this? 

Given the nature of the reconnect logic it probably isn't handy to return a promise that resolves once the connect is established given that a promise can only resolve/reject once - that is logically opposed to the idea of automatic reconnect/retry. no?

the `Topology` instance has a `connection` property which is an EventEmitter (or something compatible), which means it is possible to listen for a "connect" event on that.

what I do not quite understand is why `addConnection()` tries to establish the actual connection if you call it with a connection name that already exists ([see here](https://github.com/arobson/rabbot/blob/master/src/index.js#L98)) but does not attempt to establish the connection if you call it with a connection name it does not yet have an entry for ([see here](https://github.com/arobson/rabbot/blob/master/src/index.js#L98)) ... why the discrepancy? do I have to call `addConnection()` twice with the same args in order to get **rabbot** to attempt the actual connection? am I missing something?

I notice that `connect()` of the `Topology`s `connection` property returns a Promise - is it possible that `addConnection()` should always be returning that? [I have made a quick PR to show what I mean](https://github.com/arobson/rabbot/pull/24)
