### ISSUE TITLE
timeout vs failAfter

### ISSUE THREAD

**Issue by yamii** [arobson/rabbot#30]
what's the difference between `timeout` and `failAfter`? Sorry I seem not to comprehend those two. 
and what's the role of retryLimit with them?

**Comment by arobson** [comment]
@yamii - 
 * `timeout` - how long rabbot will wait *per connection attempt* (milliseconds)
 * `failAfter` - how long rabbot will try across *all connection attempts*
 * `retryLimit` - how many consecutive failed attempts rabbot will try to make

### Example
 * `timeout`: 2000 ms
 * `failAfter`: 30 s
 * `retryLimit`: 5

If the rabbit server was down, rabbot would try 5 times in a row, waiting 2 seconds each time before timing out. It would not matter that `failAfter` was set to 30 seconds because `retryLimit` will be reached first. This will cause rabbot to emit the `unreachable` event and stop attempting to connect. At this point, your service should call `process.exit()` with a non-zero number.
