### ISSUE TITLE
'Cannot read property 'publishTimeout' of undefined' when using retry()

### ISSUE THREAD

**Issue by bleggett** [arobson/rabbot#58]
Hi,

I've been testing how rabbot works for request-response when the service broker is taken down for some period of time.

If I set the connection `retryLimit` to a high enough value, like for instance 60, everything works as expected when connectivity to the broker is restored, even if requests were made when the broker was not accessible, i.e. once the broker comes back up I can see from rabbot's logging that it reconnects and subsequent requests work fine.

However, if I leave `retryLimit` at the default value and try to do some sort of custom retry logic using `rabbot.retry()` like so:

```
rabbot.on( 'unreachable', function() {
    for(let retries = 0; retries < 15; retries++) {
        setTimeout(() => {
        rabbot.retry();
        }, 2000);
    }
});
```

Then rabbot logging indicates it reconnects when broker connectivity is restored, as expected, but *all* subsequent attempts to use that connection will throw the error `Cannot read property 'publishTimeout' of undefined` from the requester, and I have to actually bring down both the requester and the responder to get them working again.

I have only seen this error when using `retry()` myself, the built-in retry logic using `retryLimit` does not seem to cause this problem.

**Comment by arobson** [comment]
@bleggett - are you making a call to `configure` in your code? I only ask because, unfortunately, the `retry` logic makes the assumption that everything was setup through configure. While it's the preferred way, I've noticed that not everyone uses it and it might explain the reason for the error you're getting.

**Comment by bleggett** [comment]
@arobson I am using it, but I am not invoking it again in the retry logic once the connection has been disrupted, which might be the problem.

**Comment by arobson** [comment]
@bleggett - you should only ever have to call configure once. There've been some bug fixes since but I'm still not sure how to reproduce this one if configure was used to setup the connection.

**Comment by FredyC** [comment]
Interesting. 3 years later and this error just started popping in our production. I have no reproduction either, but it's clear that the issue is still present in 2.1.0.

https://github.com/arobson/rabbot/blob/80b63c08bdb32d04fd36502f24180e0c8e8f69ee/src/index.js#L185

It might be useful to check for `options` as well. Apparently, the connection is still there but `options` is `undefined`.
