### ISSUE TITLE
Rabbot does not seem to cleanly handle broker being unreachable on startup

### ISSUE THREAD

**Issue by bleggett** [arobson/rabbot#69]
We're using docker for our app, and both the RabbitMQ broker and our Rabbot subscriber client are in different docker containers.

When our client container starts up, our rabbot subscriber client calls `rabbot.configure`, and then, assuming a resolved promise is returned, it calls `rabbot.startSubscription`

Sometimes, when we start the docker containers up, the rabbot subscriber client comes up first, before the  broker container is completely initialized.

In this case, `rabbot.configure` returns a rejected promise, and continues to retry in the background until the broker becomes reachable and rabbot reconnects.

Because rabbot immediately rejects the `configure` promise on the first connection failure (even though it continues to retry in the background, and eventually connects), I can't call `rabbot.startSubscription` in the `done` of `rabbot.configure` because there is no connection at that point.

I feel like `rabbot.configure` should not return a rejected promise until the retry limit (if configured) is exceeded.

Responder code here:

```    
    console.log('Getting connection for responder.');
    return busConnection.getConnection(rabbot).then(() => {
        console.log(`Starting responder subscription on queue ${queue}`);
        return rabbot.startSubscription(queue).then(() => {
            console.log(`Successfully started responder subscription on queue ${queue}`);
        }).catch(() => {
            console.log('Error setting up subscription');
        });
    }).catch(() => {
        console.log('Error setting up responder, maybe retry?');
        rabbot.retry();
        console.log('Retried!');
    });
```

Connection config here:
```
connection: {
            server: process.env.SERVICEBUS1_PORT_5672_TCP_ADDR,
            timeout: 10000,
            replyTimeout: 5000,
            failAfter: 30,
            retryLimit: 30,
            replyQueue: {
                name: `${os.hostname()}.${process.title}.${process.pid}.response-queue`,
                autoDelete: true,
                durable: false,
                subscribe: true,
                noAck: true
            }
        },
```

As an aside, I tried to work around this by waiting for the `configured` event to fire:

```
 rabbot.on('default.connection.configured', function() {
            console.log('Connection configured.');
        });
```

but noticed that if the initial connection attempt fails, the `finish` function in rabbot's `config.js` at line 60 is never invoked, so the configured event will never trigger for that connection.

**Summary:** If the initial connection to the broker fails in the `configure` call, rabbot will never tell me when topology is reestablished.

**Comment by iamjochem** [comment]
this is effectively the same problem as this https://github.com/arobson/rabbot/issues/27 - namely as long as you are planning to retry something the promise that reflects the result should not be resolve until after the last retry attempt has been performed.

**Comment by arobson** [comment]
@bleggett - changing the config behavior would be very difficult due to the number of failure conditions that can presently cause it to fail. Instead, I fixed the issue causing the configured event not to fire. Let me know if that's still not allowing you to get what's needed for your use case and we can re-open the issue. Thanks!

**Comment by TimBailey-pnk** [comment]
I've got the same problem where on docker startup the connection seems to be stuck in "no endpoints could be reached" even though its subsequently connected.

My case is a little different in that I'm using `rabbot.addConnection()` rather than `rabbot.configure()`.
So rabbot works perfectly in the case where rabbitmq is already running, and also when I restart the broker, it all re-connects perfectly.

But in the last case where rabbitmq is starting up and I'm also starting up, ie making the initial connection, then its stuck.  

If you have any advice on how to debug this issue that would be great.

**Comment by chriskinsman** [comment]
This should be in the docs.  Either that or a better example of how to use retry.  This issue drove me nuts for most of a day until I added the promise hack from @edorsey

I can't believe this is closed!
