### ISSUE TITLE
startSubscription is not starting subscription to the queue

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [arobson/rabbot#84]
Hi Arobson 

 i am trying to use stop and start Subscription api. I am able to stop subscription in particular condition.
 with log message 

> **2017-05-03 14:56:34.314 pid:5897 worker:1 info: Unsubscribing from queue 'NotifyServerQueue1' with tag KPNS_140./DG/Release/node/bin/node.5897.NotifyServerQueue1**

But when i was starting subscription for condition resolve then it is not starting subscription to the queue.
No log messages also printing.
Queue is also having registered handler.
```
{ name: 'NotifyServerQueue1',
 subscribe: true,
durable: true,
limit: 40,
uniqueName: 'NotifyServerQueue1',
consumerTag: 'KPNS_140./DG/Release/node/bin/node.5897.NotifyServerQueue1',
exclusive: true }
```
can you please let me know if any precondition is required for set.

Thank
Sumit.

**Comment by arobson** [comment]
@sumit-gupta-sgt if you have:

 * a connection
 * the queue was created successfully

Then subscribing works just fine. There are a ton of integration and behavior tests around this behavior. I recommend that you **do not** try to manage subscriptions yourself and instead you set `subscribe: true` on queue configuration so that it will manage it all for you.

You can see examples and read more [here](https://github.com/arobson/rabbot/blob/master/docs/topology.md#configuration-via-json-recommended).
