### ISSUE TITLE
false publish Promise

### ISSUE THREAD

**Issue by brandonpsmith** [arobson/rabbot#9]
I'm testing rabbot with a single connection to a VM of RabbitMQ. In my testing if I kill the network card to replicate a lost connection, the publish still resolves until failed is emitted. Can you double check this?

**Comment by arobson** [comment]
@brandonpsmith - I found the problem, despite how the documentation of the amqplib is written, the publish call behaves differently from sendToQueue, and returns true or false, rather than a promise. The way the iomonad around channels in rabbot behaves is that it resolves the promise if the underlying result of a call is a scalar value instead of a promise itself.

It looks like the publish call in amqplib does take a old-school callback but there is nothing in the documentation about it. I'll have to do some experimenting to see if that will resolve the issue.

**Comment by arobson** [comment]
@brandonpsmith - I think I have a fix for this, based on what you described. I don't currently have a test for it since I'll need to find a way to kill/restore TCP/IP connectivity via Node in a test (that would be fun).

I did some manual testing from a REPL though and was finally getting rejected promises. Let me know if this appears to be working for you. I'll wait a day or so before closing the defect.
