### ISSUE TITLE
Use bluebird for promises to resolve issues with CLS

### ISSUE THREAD

**Issue by mrfelton** [arobson/rabbot#94]
Currently Rabbot uses the When promise library. This is known to break things that use [CLS](https://github.com/othiym23/node-continuation-local-storage) or [CLS Hooked](https://github.com/Jeff-Lewis/cls-hooked) such as https://github.com/strongloop/loopback-context.

Other promise libraries such as [Bluebird](https://github.com/petkaantonov/bluebird) do not have these issues.

Either this module should use Bluebird for it's promises, it should use global.Promise, or (preferably) it should allow the user to determine which promise library is used.

**Comment by ptusch** [comment]
*Bump* Would love this feature as well. :)

**Comment by weyert** [comment]
This would indeed be a lovely addition to the library!

**Comment by arobson** [comment]
@mrfelton @ptusch @weyert  For now I've just dropped back to native Promises since v2 supports Node 6 and 8 (not supporting 4 anymore).

This shouldn't break anything else but if there's a very compelling reason, I will look at adding a dependency back to it. I've tried to strip down/simplify rabbot's dependency tree considerably (and might continue to).
